export const HOLDING_LIST_REQUEST = 'HOLDING_LIST_REQUEST'
export const HOLDING_LIST_SUCCESS = 'HOLDING_LIST_SUCCESS'
export const HOLDING_LIST_FAIL = 'HOLDING_LIST_FAIL'

export const ADD_COIN_REQUEST = 'ADD_COIN_REQUEST'
export const ADD_COIN_SUCCESS = 'ADD_COIN_SUCCESS'
export const ADD_COIN_FAIL = 'ADD_COIN_FAIL'

export const DELETE_COIN = 'DELETE_COIN'